---

- name: patch the nginx.conf include site-availability , default server entry
  patch: #this patch module has root privilage
    src: files/nginx.conf.redhat.patch
    dest: /etc/nginx/nginx.conf
  when: ansible_distribution == "RedHat"
- name: create a directory /etc/nginx/sites-available
  file:
    path: /etc/nginx/sites-available
    state: directory
  when: ansible_distribution == "RedHat"
- name: create a directory /etc/nginx/sites-enabled
  file:
    path: /etc/nginx/sites-enabled
    state: directory
  when: ansible_distribution == "RedHat"
- name: copy the default nginx configuration
  copy:
    src: files/nginx-default.conf
    dest: /etc/nginx/sites-available/default
  when: ansible_distribution == "RedHat"
- name: create a symbolic link /etc/nginx/sites-available/default to /etc/nginx/sites-enablehd/default
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  when: ansible_distribution == "RedHat"
- name: we will create push our own file using jinja 2 template
  template:
    src: templates/index.html.j2
    dest: /usr/share/nginx/html/index.html
    mode: 0644
  when: ansible_distribution == "RedHat"
- name: restart nginx server
  service:
      #systemctl restart httpd service
    name: nginx
    state: restarted
  notify: check http service
  when: ansible_distribution == "RedHat"
- name: add port in firewalld
    #by default when you install redhat it get installed with firewalld a inbuilt firewall in your redhat based system
  firewalld:
    service: http
    permanent: true
    state: enabled
  when: ansible_distribution == "RedHat"
  notify: Reload Firewalld
